name: CI

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v12

      - name: Cachix
        uses: cachix/cachix-action@v10
        with:
          name: haskell-org
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build Site
        # we run the checks as a separate step
        run: >
          nix build \
            --verbose \
            --print-build-logs \
            --file . \
            built -o built-site \
            --arg doCheck false \
            --extra-experimental-features nix-command

      - name: Check Links
        run: >
          nix shell \
            --quiet \
            --file . \
            linkchecker \
            --extra-experimental-features nix-command
            --command linkchecker built-site


      - uses: actions/upload-artifact@v2
        with:
          name: www.haskell.org
          path: built-site*  # Uses glob pattern because
                             # actions/upload-artifact@v2 gets
                             # confused by symlinks otherwise
                             #
                             # See:
                             # https://github.com/actions/upload-artifact/issues/92
